### ISSUE TITLE
Request to modify norm_sspec function

### ISSUE THREAD

**Issue by jturner28** [danielreardon/scintools#10]
It would be nice to have access to the fdopnew and isspecavg arrays in the norm_sspec function for the purpose of more in-depth arc asymmetry analyses outside of simply plotting. It's easy enough to modify the source code to obtain them, but it would be nice if this was an existing feature.

**Comment by danielreardon** [comment]
Hi @jturner28 , those arrays are saved as `self.normsspec_fdop` and `self.normsspecavg` respectively. So if you run the norm_sspec function without plotting (which I believe is default), they will be attributes of your Dynspec object, so you can access them that way. 

```
dyn = Dynspec(filename)  # load dynamic spectrum given by filename
dyn.norm_sspec(eta=100)  # form normalised secondary spectrum with respect to curvature=100

# Get the desired arrays
fdopnew = dyn.normsspec_fdop
isspecavg = dyn.normsspecavg
```

Is that what you were looking for or did I misunderstand?

**Comment by jturner28** [comment]
That's perfect. Thanks for your help.
